#!/bin/sh

set -e

source "$(dirname $0)/common.sh"

payload=`cat`
bucket=$(get_bucket)
prefix=$(get_prefix)
aws_options=$(echo "$payload" | jq -r '.source.aws_options // [] | join(" ")')

export_aws_vars

# https://concourse-ci.org/docs/resource-types/implementing/
recent=$(get_last_version)
jq -n --arg timestamp "$recent" \
  '[{version: $timestamp}]'
