#!/bin/sh

set -e

cwd=$(dirname $0)

source "${cwd}/common.sh"
source "${cwd}/read_params.sh"

export_aws_vars

# https://concourse-ci.org/docs/resource-types/implementing/
timestamp=$(get_last_modified)
jq -n --arg timestamp "$timestamp" \
  '[{LastModified: $timestamp}]'
