#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

dest=$1

if [ -z "$dest" ]; then
  echo "usage: $0 <path/to/volume>"
  exit 1
fi

cwd=$(dirname $0)

source "${cwd}/common.sh"
source "${cwd}/read_params.sh"
export_aws_vars

if [ "$skip_download" = "true" ]; then
  echo "Skipping download from S3"
else
  echo "Downloading from '${bucket_uri}' using ${command}..."
  eval aws ${aws_options} s3 ${command} "${bucket_uri}" ${dest} ${options}
  echo "Done."
fi

emit_version >&3
