#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

dest=$1

if [ -z "${dest}" ]; then
  echo "usage: $0 <path/to/volume>"
  exit 1
fi

cwd=$(dirname $0)
source "${cwd}/setup.sh"

last_modified=$(get_last_modified)

echo "Downloading from ${bucket}/${prefix} using ${command}..."
rc ${command} "local/${bucket}/${prefix}" "${dest}" ${global_options} ${local_options}
echo "Done"

jq -n --arg last_modified "${last_modified}" \
  '{version: { LastModified: $last_modified }}'\
  >&3
