#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir>"
  exit 1
fi

cwd=$(dirname $0)

source "${cwd}/common.sh"
source "${cwd}/read_params.sh"
test -z "${source_dir}" && { echo "Must supply params.source_dir" >&2; exit 1; }

export_aws_vars

dir="${source}/${source_dir}"
echo "Uploading '${dir}' to '${bucket_uri}' using ${command}..."
eval aws ${aws_options} s3 sync "${dir}" "${bucket_uri}" ${options}
echo "Done."

emit_version >&3
